#�û��� ��������
security:
  user:
    name: admin
    password: test
##�˿ں�
#���÷���·�����������ʱΪhttp://localhost:8081/demo/..
server:
   context-path: /demo
   port: 8082
spring:
   jackson:
      serialization:
          write-dates-as-timestamps: false